# -*- coding: utf-8 -*-
"""Interactive_Media_Intelligence_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rjyhy2BSgWcqoibjfdoywcn3DtDPJo2L

# 📊 Interactive Media Intelligence Dashboard

## 📥 Step 1: Upload Your CSV File
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

# Load the CSV
for file_name in uploaded.keys():
    df = pd.read_csv(file_name)
    print(f"Loaded {file_name} with shape {df.shape}")

"""## 🧹 Step 2: Clean the Data"""

# Normalize column names
df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]

# Convert date to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Fill missing engagements with 0
df['engagements'] = pd.to_numeric(df['engagements'], errors='coerce').fillna(0)

# Display cleaned data
df.head()

"""## 📊 Step 3: Visualize the Data with Plotly"""

import plotly.express as px
import plotly.graph_objects as go
from IPython.display import display, Markdown

"""### 🥧 Sentiment Breakdown"""

fig_sentiment = px.pie(df, names='sentiment', title='Sentiment Breakdown')
fig_sentiment.show()

# Insights
sentiment_counts = df['sentiment'].value_counts()
top_sentiments = sentiment_counts.head(3)
display(Markdown("**Top 3 Sentiment Insights:**"))
for i, (sentiment, count) in enumerate(top_sentiments.items(), 1):
    display(Markdown(f"{i}. **{sentiment}** appears {count} times."))

"""### 📈 Engagement Trend Over Time"""

engagement_trend = df.groupby('date')['engagements'].sum().reset_index()
fig_line = px.line(engagement_trend, x='date', y='engagements', title='Engagement Trend Over Time')
fig_line.show()

top_days = engagement_trend.sort_values('engagements', ascending=False).head(3)
display(Markdown("**Top 3 Engagement Dates:**"))
for i, row in top_days.iterrows():
    display(Markdown(f"{i+1}. **{row['date'].date()}** with {int(row['engagements'])} engagements"))

"""### 📊 Platform Engagements"""

platform_engagements = df.groupby('platform')['engagements'].sum().reset_index()
fig_platform = px.bar(platform_engagements, x='platform', y='engagements', title='Platform Engagements')
fig_platform.show()

top_platforms = platform_engagements.sort_values('engagements', ascending=False).head(3)
display(Markdown("**Top 3 Platforms:**"))
for i, row in top_platforms.iterrows():
    display(Markdown(f"{i+1}. **{row['platform']}** with {int(row['engagements'])} engagements"))

"""### 🧾 Media Type Mix"""

fig_media = px.pie(df, names='media_type', title='Media Type Mix')
fig_media.show()

media_counts = df['media_type'].value_counts().head(3)
display(Markdown("**Top 3 Media Types:**"))
for i, (media, count) in enumerate(media_counts.items(), 1):
    display(Markdown(f"{i}. **{media}** appears {count} times."))

"""### 🌍 Top 5 Locations by Engagement"""

location_engagements = df.groupby('location')['engagements'].sum().reset_index()
top_locations = location_engagements.sort_values('engagements', ascending=False).head(5)
fig_location = px.bar(top_locations, x='location', y='engagements', title='Top 5 Locations by Engagement')
fig_location.show()

display(Markdown("**Top 3 Locations:**"))
for i, row in top_locations.head(3).iterrows():
    display(Markdown(f"{i+1}. **{row['location']}** with {int(row['engagements'])} engagements"))